-- Generated by Matugen
local M = {}

M.base_30 = {
	white = "{{colors.on_surface.default.hex}}",
	darker_black = "{{colors.surface_container_lowest.default.hex}}",
	black = "{{colors.surface.default.hex}}",
	black2 = "{{colors.surface_container_low.default.hex}}",
	one_bg = "{{colors.surface_container.default.hex}}",
	one_bg2 = "{{colors.surface_container_high.default.hex}}",
	one_bg3 = "{{colors.surface_dim.default.hex}}",
	grey = "{{colors.outline_variant.default.hex}}",
	grey_fg = "{{colors.on_surface_variant.default.hex}}",
	grey_fg2 = "{{colors.outline.default.hex}}",
	light_grey = "{{colors.on_surface_variant.default.hex}}",
	red = "{{colors.error.default.hex}}",
	baby_pink = "{{colors.tertiary.default.hex}}",
	pink = "{{colors.tertiary.default.hex}}",
	line = "{{colors.outline.default.hex}}",
	green = "{{colors.primary.default.hex}}",
	vibrant_green = "{{colors.primary_fixed_dim.default.hex}}",
	nord_blue = "{{colors.secondary_container.default.hex}}",
	blue = "{{colors.secondary.default.hex}}",
	yellow = "{{colors.tertiary.default.hex}}",
	sun = "{{colors.tertiary_fixed_dim.default.hex}}",
	purple = "{{colors.tertiary.default.hex}}",
	dark_purple = "{{colors.tertiary_container.default.hex}}",
	teal = "{{colors.tertiary_fixed.default.hex}}",
	orange = "{{colors.error_container.default.hex}}",
	cyan = "{{colors.secondary_container.default.hex}}",
	statusline_bg = "{{colors.surface_container_lowest.default.hex}}",
	lightbg = "{{colors.surface_container.default.hex}}",
	pmenu_bg = "{{colors.primary_container.default.hex}}",
	folder_bg = "{{colors.secondary.default.hex}}",
	lavender = "{{colors.secondary_container.default.hex}}",
}

M.base_16 = {
	base00 = "{{colors.surface.default.hex}}",
	base01 = "{{colors.surface_container_low.default.hex}}",
	base02 = "{{colors.surface_container.default.hex}}",
	base03 = "{{colors.surface_container_high.default.hex}}",
	base04 = "{{colors.outline_variant.default.hex}}",
	base05 = "{{colors.on_surface.default.hex}}",
	base06 = "{{colors.on_surface_variant.default.hex}}",
	base07 = "{{colors.surface_bright.default.hex}}",
	base08 = "{{colors.error.default.hex}}",
	base09 = "{{colors.tertiary.default.hex}}",
	base0A = "{{colors.secondary.default.hex}}",
	base0B = "{{colors.primary.default.hex}}",
	base0C = "{{colors.tertiary_fixed.default.hex}}",
	base0D = "{{colors.primary_fixed.default.hex}}",
	base0E = "{{colors.tertiary.default.hex}}",
	base0F = "{{colors.error_container.default.hex}}",
}

M.polish_hl = {
	treesitter = {
		["@variable"] = { fg = "{{colors.secondary_container.default.hex}}" },
		["@property"] = { fg = "{{colors.tertiary_fixed.default.hex}}" },
		["@variable.builtin"] = { fg = "{{colors.error.default.hex}}" },
	},
}

M.type = "dark"

return M
