-- Generated by Matugen
local M = {}

M.base_30 = {
	white = "#e1e2e9",
	darker_black = "#0c0e13",
	black = "#111318",
	black2 = "#191c20",
	one_bg = "#1d2024",
	one_bg2 = "#282a2f",
	one_bg3 = "#111318",
	grey = "#43474e",
	grey_fg = "#c4c6cf",
	grey_fg2 = "#8e9199",
	light_grey = "#c4c6cf",
	red = "#ffb4ab",
	baby_pink = "#dbbce1",
	pink = "#dbbce1",
	line = "#8e9199",
	green = "#a8c8ff",
	vibrant_green = "#a8c8ff",
	nord_blue = "#3e4758",
	blue = "#bdc7dc",
	yellow = "#dbbce1",
	sun = "#dbbce1",
	purple = "#dbbce1",
	dark_purple = "#563e5d",
	teal = "#f8d8fe",
	orange = "#93000a",
	cyan = "#3e4758",
	statusline_bg = "#0c0e13",
	lightbg = "#1d2024",
	pmenu_bg = "#254777",
	folder_bg = "#bdc7dc",
	lavender = "#3e4758",
}

M.base_16 = {
	base00 = "#111318",
	base01 = "#191c20",
	base02 = "#1d2024",
	base03 = "#282a2f",
	base04 = "#43474e",
	base05 = "#e1e2e9",
	base06 = "#c4c6cf",
	base07 = "#37393e",
	base08 = "#ffb4ab",
	base09 = "#dbbce1",
	base0A = "#bdc7dc",
	base0B = "#a8c8ff",
	base0C = "#f8d8fe",
	base0D = "#d5e3ff",
	base0E = "#dbbce1",
	base0F = "#93000a",
}

M.polish_hl = {
	treesitter = {
		["@variable"] = { fg = "#3e4758" },
		["@property"] = { fg = "#f8d8fe" },
		["@variable.builtin"] = { fg = "#ffb4ab" },
	},
}

M.type = "dark"

return M
